# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20160829194324) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "colonies", force: :cascade do |t|
    t.text     "issues_found"
    t.text     "login_email_address"
    t.integer  "colony_number"
    t.float    "year_active"
    t.text     "colony_name"
    t.text     "colony_city"
    t.text     "colony_street_address"
    t.text     "colony_intersection_first_street"
    t.text     "colony_intersection_second_street"
    t.string   "colony_ward"
    t.text     "colony_setting"
    t.text     "batchgeo_address"
    t.integer  "map_street_number"
    t.text     "map_street_name"
    t.text     "map_city_name"
    t.text     "map_postal_code"
    t.text     "is_colony_registered_with_another_organization"
    t.text     "registered_with_which_organization"
    t.text     "primary_first_name"
    t.text     "primary_last_name"
    t.text     "primary_phone"
    t.text     "primary_cell_or_work_number"
    t.text     "primary_email"
    t.text     "primary_alternate_email"
    t.text     "member_of_org_or_rescue_org"
    t.text     "which_organization"
    t.text     "attended_feral_colony_workshop"
    t.text     "secondary_first_name"
    t.text     "secondary_last_name"
    t.text     "secondary_phone"
    t.text     "secondary_cell"
    t.text     "secondary_email"
    t.text     "secondary_alternate_email"
    t.text     "which_org_or_rescue_org"
    t.text     "have_you_attended_workshop_on_feral_cat_management"
    t.text     "do_you_know_previous_caretaker"
    t.float    "male_count"
    t.float    "female_count"
    t.float    "undetermined_count"
    t.integer  "kitten_count"
    t.float    "male_deaths_natural"
    t.float    "male_deaths_suspicious"
    t.float    "male_deaths_euthanasia"
    t.integer  "male_deaths_predator"
    t.integer  "male_deaths_car_or_accident"
    t.integer  "female_deaths_natural"
    t.float    "female_deaths_suspicious"
    t.float    "female_deaths_euthanasia"
    t.float    "female_deaths_predator"
    t.integer  "female_deaths__car_or_accident"
    t.float    "undetermined_deaths_natural"
    t.float    "undetermined_deaths_suspicious"
    t.float    "undetermined_deaths_euthanasia"
    t.integer  "undetermined_deaths_predator"
    t.integer  "undetermined_deaths_car_or_accident"
    t.integer  "kitten_deaths_natural"
    t.integer  "kitten_deaths_suspicious"
    t.integer  "kitten_deaths_euthanasia"
    t.integer  "kitten_deaths_predator"
    t.integer  "kitten_deaths_car_or_accident"
    t.float    "male_disappearances"
    t.float    "female_disappearances"
    t.float    "undetermined_disappearances"
    t.integer  "kitten_disappearances"
    t.text     "do_you_have_problems_with_predators"
    t.text     "coyote_problems"
    t.text     "racoon_problems"
    t.text     "other_predator_problems"
    t.integer  "number_of_male_cats_added_to_colony"
    t.integer  "number_of_female_cats_added_to_colony"
    t.integer  "number_of_undetermined_cats_added_to_colony"
    t.text     "were_tnrd_cats_returned_to_colony"
    t.text     "were_tnrd_cats_documentedphotographed"
    t.float    "spayed"
    t.float    "neutered"
    t.text     "early_age_spaying"
    t.text     "early_age_neutering"
    t.text     "where_were_cats_sn"
    t.text     "why_did_you_use_the_sn_services_you_did"
    t.text     "how_long_to_get_sn_appointment"
    t.integer  "most_cats_sn_at_one_time"
    t.text     "how_did_you_get_to_clinic"
    t.text     "did_you_have_other_drivers"
    t.text     "where_did_cats_recover"
    t.text     "how_did_cats_recover"
    t.text     "number_days_of_recovery_female"
    t.text     "number_days_of_recovery_kittens"
    t.text     "were_cats_eartipped"
    t.text     "were_cats_vaccinated"
    t.text     "were_cats_microchipped"
    t.float    "male_returned_to_colony"
    t.float    "female_returned_to_colony"
    t.integer  "kittens_returned_to_colony"
    t.text     "male_fostered_adopted"
    t.text     "female_fostered_adopted"
    t.text     "kittens_fostered_adopted"
    t.text     "trapping_resources"
    t.integer  "number_of_owned_traps"
    t.integer  "number_of_borrowed_traps"
    t.text     "borrowed_traps_from_where"
    t.text     "borrowed_carriers_for_what_purpose"
    t.text     "did_you_have_help_trapping"
    t.integer  "how_many_people_helpd_you_trap"
    t.text     "trappers_came_from_where"
    t.float    "total_sn_expenses_to_date"
    t.float    "expenses_to_date_for_medical_care_or_emergencies"
    t.float    "colony_expenses_per_week"
    t.text     "received_money_or_free_food_to_help"
    t.text     "issues_you_have_with_neighbours_etc"
    t.text     "free_roaming_cats_in_area"
    t.text     "owned_but_unaltered_allowed_to_roam"
    t.text     "are_cats_abandoned_near_your_colony"
    t.integer  "number_of_cats_abandoned_per_year_near_colony"
    t.text     "did_you_try_to_educate_neighbours_about_tnr"
    t.text     "neighbourhood_advised_re_tnr_occuring"
    t.text     "did_you_advise_others_not_to_feed_cats"
    t.text     "did_you_advise_neighbourhood_how_successful_tnr_is"
    t.text     "how_did_you_advise_neighbours_re_tnr_success"
    t.text     "cats_threatened_poisoned_or_killed"
    t.text     "you_or_family_been_threatenedharmed"
    t.text     "home_or_property_vandalized_due_to_cats"
    t.text     "police_bylaw_enforcement_or_animal_services_contacted"
    t.text     "what_was_the_issue_for_police_etc"
    t.text     "was_issue_resolved"
    t.text     "is_local_govmt_feral_friendly"
    t.text     "local_govmt_supports_tnr"
    t.text     "how_does_local_govmt_support_tnr"
    t.text     "do_you_have_help_caring_for_colony"
    t.text     "how_often_do_others_help"
    t.text     "how_do_others_help_you"
    t.text     "how_often_do_you_feed_the_colony"
    t.text     "what_time_of_day_do_you_feed_colony"
    t.text     "feed_in_dishes"
    t.text     "fed_open_station"
    t.text     "fed_building"
    t.text     "feeding_station"
    t.text     "fed_covered_station"
    t.text     "feed_in_dishes_on_ground"
    t.text     "food_directly_on_ground"
    t.text     "feed_in_other_circumstances"
    t.string   "do_you_feed_wet_food"
    t.text     "do_you_feed_dry_food"
    t.text     "do_you_feed_supplementsvitamins"
    t.text     "do_you_feed_naturopathic_or_other"
    t.integer  "how_many_shelters_are_in_place"
    t.integer  "how_many_styrofoam_shelters"
    t.integer  "how_many_plastic_lined_with_styrofoam"
    t.integer  "how_many_wooden_shelters"
    t.integer  "how_many_cardboard_shelters"
    t.integer  "how_many_other_shelters_in_place"
    t.text     "do_you_change_straw_in_spring_and_fall"
    t.text     "do_you_have_difficulty_finding_straw"
    t.text     "overall_condition_of_colony"
    t.text     "disease_or_ongoing_health_concerns_in_colony"
    t.text     "describe_ongoing_cat_health_concerns_briefly"
    t.text     "are_you_a_member_of_toronto_feral_cat_yahoo_group"
    t.text     "are_you_a_member_of_toronto_feral_cat_facebook_group"
    t.text     "are_you_a_member_of_toronto_feral_cat_other_group"
    t.text     "interested_in_seminar_on_caretaker_burnout"
    t.text     "interested_in_seminar_on_situational_awareness"
    t.text     "interested_in_self_defence"
    t.text     "any_suggestions_for_other_seminars"
    t.text     "what_support_would_help_you_with_your_colony"
    t.text     "what_is_your_greatest_challenge"
    t.text     "would_you_be_interested_in_helping_other_colony_caretakers"
    t.datetime "created_at",                                                 null: false
    t.datetime "updated_at",                                                 null: false
    t.boolean  "secondary_member_of_org_or_rescue_org"
    t.integer  "number_days_of_recovery_male"
    t.float    "neighbourhood_statisfaction_to_cats"
    t.integer  "neighbourhood_satisfaction_to_you_and_tnr_efforts"
  end

end
