class ChangeDataType < ActiveRecord::Migration
  def change
        change_column :colonies, :login_email_address, :text
        change_column :colonies, :year_active, :float
        change_column :colonies, :colony_name, :text
        change_column :colonies, :colony_city, :text
        change_column :colonies, :colony_street_address, :text
        change_column :colonies, :colony_intersection_first_street, :text
        change_column :colonies, :colony_intersection_second_street, :text
        change_column :colonies, :colony_setting, :text
        change_column :colonies, :batchgeo_address, :text
        change_column :colonies, :map_street_name, :text
        change_column :colonies, :map_city_name, :text
        change_column :colonies, :map_postal_code, :text
        change_column :colonies, :is_colony_registered_with_another_organization, :text
        change_column :colonies, :registered_with_which_organization, :text
        change_column :colonies, :primary_first_name, :text
        change_column :colonies, :primary_last_name, :text
        change_column :colonies, :primary_phone, :text
        change_column :colonies, :primary_cell_or_work_number, :text
        change_column :colonies, :primary_email, :text
        change_column :colonies, :primary_alternate_email, :text
        change_column :colonies, :member_of_org_or_rescue_org, :text
        change_column :colonies, :which_organization, :text
        change_column :colonies, :attended_feral_colony_workshop, :text
        change_column :colonies, :secondary_first_name, :text
        change_column :colonies, :secondary_last_name, :text
        change_column :colonies, :secondary_phone, :text
        change_column :colonies, :secondary_cell, :text
        change_column :colonies, :secondary_email, :text
        change_column :colonies, :secondary_alternate_email, :text
        change_column :colonies, :member_of_org_or_rescue_org, :text
        change_column :colonies, :which_org_or_rescue_org, :text
        change_column :colonies, :have_you_attended_workshop_on_feral_cat_management, :text
        change_column :colonies, :do_you_know_previous_caretaker, :text
        change_column :colonies, :male_count, :float
        change_column :colonies, :female_count, :float
        change_column :colonies, :undetermined_count, :float
        change_column :colonies, :male_deaths_natural, :float
        change_column :colonies, :male_deaths_suspicious, :float
        change_column :colonies, :male_deaths_euthanasia, :float
        change_column :colonies, :female_deaths_suspicious, :float
        change_column :colonies, :female_deaths_euthanasia, :float
        change_column :colonies, :female_deaths_predator, :float
        change_column :colonies, :undetermined_deaths_natural, :float
        change_column :colonies, :undetermined_deaths_suspicious, :float
        change_column :colonies, :undetermined_deaths_euthanasia, :float
        change_column :colonies, :male_disappearances, :float
        change_column :colonies, :female_disappearances, :float
        change_column :colonies, :undetermined_disappearances, :float
        change_column :colonies, :do_you_have_problems_with_predators, :text
        change_column :colonies, :coyote_problems, :text
        change_column :colonies, :racoon_problems, :text
        change_column :colonies, :other_predator_problems, :text
        change_column :colonies, :were_tnrd_cats_returned_to_colony, :text
        change_column :colonies, :were_tnrd_cats_documentedphotographed, :text
        change_column :colonies, :spayed, :float
        change_column :colonies, :neutered, :float
        change_column :colonies, :early_age_spaying, :text
        change_column :colonies, :early_age_neutering, :text
        change_column :colonies, :where_were_cats_sn, :text
        change_column :colonies, :how_long_to_get_sn_appointment, :text
        change_column :colonies, :did_you_have_other_drivers, :text
        change_column :colonies, :where_did_cats_recover, :text
        
        change_column :colonies, :number_days_of_recovery_female, :text
        change_column :colonies, :number_days_of_recovery_kittens, :text
        change_column :colonies, :were_cats_eartipped, :text
        change_column :colonies, :were_cats_vaccinated, :text
        change_column :colonies, :were_cats_microchipped, :text
        change_column :colonies, :male_returned_to_colony, :float
        change_column :colonies, :female_returned_to_colony, :float
        change_column :colonies, :male_fostered_adopted, :text
        change_column :colonies, :female_fostered_adopted, :text
        change_column :colonies, :kittens_fostered_adopted, :text
        change_column :colonies, :trapping_resources, :text
        change_column :colonies, :borrowed_traps_from_where, :text
        change_column :colonies, :borrowed_carriers_for_what_purpose, :text
        change_column :colonies, :did_you_have_help_trapping, :text
        change_column :colonies, :trappers_came_from_where, :text
        change_column :colonies, :total_sn_expenses_to_date, :float
        change_column :colonies, :expenses_to_date_for_medical_care_or_emergencies, :float
        change_column :colonies, :colony_expenses_per_week, :float
        change_column :colonies, :received_money_or_free_food_to_help, :text
        
        
        change_column :colonies, :free_roaming_cats_in_area, :text
        change_column :colonies, :owned_but_unaltered_allowed_to_roam, :text
        change_column :colonies, :are_cats_abandoned_near_your_colony, :text
        change_column :colonies, :did_you_try_to_educate_neighbours_about_tnr, :text
        change_column :colonies, :neighbourhood_advised_re_tnr_occuring, :text
        change_column :colonies, :did_you_advise_others_not_to_feed_cats, :text
        change_column :colonies, :did_you_advise_neighbourhood_how_successful_tnr_is, :text
        change_column :colonies, :cats_threatened_poisoned_or_killed, :text
        change_column :colonies, :you_or_family_been_threatenedharmed, :text
        change_column :colonies, :home_or_property_vandalized_due_to_cats, :text
        change_column :colonies, :police_bylaw_enforcement_or_animal_services_contacted, :text
        change_column :colonies, :was_issue_resolved, :text
        change_column :colonies, :is_local_govmt_feral_friendly, :text
        change_column :colonies, :local_govmt_supports_tnr, :text
        change_column :colonies, :do_you_have_help_caring_for_colony, :text
        change_column :colonies, :how_often_do_others_help, :text
        change_column :colonies, :how_often_do_you_feed_the_colony, :text
        change_column :colonies, :what_time_of_day_do_you_feed_colony, :text
        change_column :colonies, :feed_in_dishes, :text
        change_column :colonies, :fed_open_station, :text
        change_column :colonies, :fed_building, :text
        change_column :colonies, :feeding_station, :text
        change_column :colonies, :fed_covered_station, :text
        change_column :colonies, :feed_in_dishes_on_ground, :text
        change_column :colonies, :food_directly_on_ground, :text
        change_column :colonies, :feed_in_other_circumstances, :text
        change_column :colonies, :do_you_feed_wet_food, :string
        change_column :colonies, :do_you_feed_dry_food, :text
        change_column :colonies, :do_you_feed_supplementsvitamins, :text
        change_column :colonies, :do_you_feed_naturopathic_or_other, :text
        change_column :colonies, :do_you_change_straw_in_spring_and_fall, :text
        change_column :colonies, :do_you_have_difficulty_finding_straw, :text
        change_column :colonies, :disease_or_ongoing_health_concerns_in_colony, :text
        change_column :colonies, :are_you_a_member_of_toronto_feral_cat_yahoo_group, :text
        change_column :colonies, :are_you_a_member_of_toronto_feral_cat_facebook_group, :text
        change_column :colonies, :are_you_a_member_of_toronto_feral_cat_other_group, :text
        change_column :colonies, :interested_in_seminar_on_caretaker_burnout, :text
        change_column :colonies, :interested_in_seminar_on_situational_awareness, :text
        change_column :colonies, :interested_in_self_defence, :text
        change_column :colonies, :would_you_be_interested_in_helping_other_colony_caretakers, :text
  end



end
